dist: xenial
language: node_js
sudo: required


branches:
  only:
    - master

install:
  # It seems to be a good idea to clean before install
  # see https://travis-ci.community/t/i-needed-an-explicit-cleanup-before-starting-my-tests-to-have-then-working-again-is-that-normal/5512/2
  - npm run clean
  - npm install

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 12"
      node_js: 12

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      node_js: 10

      script:
        - npm run lint:md
        - npm run lint:text
