#!/bin/bash
#
# Copyright 2020 FIWARE Foundation e.V.
#
# This file is part of iotagent-isoxml
#
# iotagent-isoxml is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# iotagent-isoxml is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#

docker build --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
	--label "org.opencontainers.image.created"=$(date +%Y-%m-%d) \
	--label "org.opencontainers.image.revision"=$SOURCE_COMMIT \
	--label "org.opencontainers.image.version"=$DOCKER_TAG \
	-t $IMAGE_NAME .

docker build --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
	--label "org.opencontainers.image.created"=$(date +%Y-%m-%d) \
	--label "org.opencontainers.image.revision"=$SOURCE_COMMIT \
	--label "org.opencontainers.image.version"=$DOCKER_TAG \
	--target=pm2
	-t $IMAGE_NAME-pm2 .

docker build --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
	--label "org.opencontainers.image.created"=$(date +%Y-%m-%d) \
	--label "org.opencontainers.image.revision"=$SOURCE_COMMIT \
	--label "org.opencontainers.image.version"=$DOCKER_TAG \
	--target=distroless
	-t $IMAGE_NAME-distroless .
