name: Anchore Security Scan for Node Slim

on:
    release:
        types: [published]
    schedule:
        - cron: "0 8 * * 1"
    workflow_dispatch:

jobs:
    anchore:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build node-slim container
              uses: docker/build-push-action@v2
              with:
                  context: ./docker
                  tags: localbuild/node-slim:latest
                  push: false
                  load: true
            - name: Security Scan for node-slim Image
              uses: anchore/scan-action@v3
              id: scan-base
              with:
                  image: "localbuild/node-slim:latest"
                  acs-report-enable: true
                  severity-cutoff: critical
            - name: Upload Node-Slim Report
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: node-slim-report
                  path: ${{ steps.scan-base.outputs.sarif }}
            - name: upload Anchore scan SARIF report
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                  sarif_file: ${{ steps.scan-base.outputs.sarif }}
